DA: false
arcface: false
batchsize: 32
circle: false
color_jitter: false
contrast: false
cosface: false
data_dir: /content/drive/MyDrive/University-Release/train
droprate: 0.5
erasing_p: 0
extra_Google: false
fp16: false
gpu_ids: '0'
h: 384
lifted: false
loss_merge: false
lr: 0.01
moving_avg: 1.0
name: ft_ResNet50_3
nclasses: 701
pad: 10
pool: avg
resume: false
share: false
sphere: false
stride: 2
train_all: true
triplet: false
use_NAS: false
use_dense: false
views: 2
w: 384
warm_epoch: 0
